#:kivy 2.0.0

<MainWindows>
    orientation: "vertical"

    TopPanelBar:
        size_hint: 1, 0.05
#    ToggleButton:
#        text: root.my_text
#        on_state: root.toggle_method_def(self)
    TaskScrollView:

#    Button:
#        text: "0"
#        on_press: root.ons(self)

<TaskScrollView@ScrollView>
    TaskBar:
        size_hint: 1, None
        height: "1000dp"
        Task:

<Task>
    orientation: "horizontal"
    #size_hint: 1, 0.1
    Label:
        # size_hint: 1, 0.3
        text: "0"
    Button:
        text: "1"

    Label:
        # size_hint: 1, 0.3
        text: "0"
    Switch:
        on_state:



<TopPanelBar>
    orientation: "horizontal"
    Button:
        text: "M"
        size_hint: 0.1,  1
    Button:
        size_hint: 0.8,  1
        text: 'Hello from test.kv'
    Button:
        size_hint: 0.1, 1
        text: 'log in'


        # height: "50dp"
        # x, center_x, right
        # y, center_y, right
        # pos_hint: {"center_y": 1, "center_x": 0}